//Autogenerated by SSDCPortal.EntityGenerator
using SSDCPortal.Constants;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace SSDCPortal.Shared.DataInterfaces
{
    public interface IApplicationUserRole
    {
        string TenantId { get; set; }

        IApplicationUser User { get; set; }

        IApplicationRole Role { get; set; }

        Guid UserId { get; set; }

        Guid RoleId { get; set; }

    }
}
