//Autogenerated by SSDCPortal.EntityGenerator
using SSDCPortal.Constants;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace SSDCPortal.Shared.DataInterfaces
{
    public interface IDbLog
    {
        Int32 Id { get; set; }

        String Message { get; set; }

        String MessageTemplate { get; set; }

        String Level { get; set; }

        DateTime TimeStamp { get; set; }

        String Exception { get; set; }

        String Properties { get; set; }

    }
}
