//Autogenerated by SSDCPortal.EntityGenerator
using SSDCPortal.Constants;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace SSDCPortal.Shared.DataInterfaces
{
    public interface IPluralFormRule
    {
        String Language { get; set; }

        Int32 Count { get; set; }

        String Selector { get; set; }

    }
}
