//Autogenerated by SSDCPortal.EntityGenerator
using SSDCPortal.Constants;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace SSDCPortal.Shared.DataInterfaces
{
    public interface IPluralTranslation
    {
        Int64 Id { get; set; }

        Int32 Index { get; set; }

        String Translation { get; set; }

        Int64 LocalizationRecordId { get; set; }

        ILocalizationRecord LocalizationRecord { get; set; }

    }
}
