//Autogenerated by SSDCPortal.EntityGenerator
using SSDCPortal.Constants;
using SSDCPortal.Shared.DataInterfaces;
using Breeze.Sharp;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace SSDCPortal.Shared.Dto.Db
{
    public partial class PluralFormRule : BaseEntity, IPluralFormRule
    {
        public String Language
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public Int32 Count
        {
            get { return GetValue<Int32>(); }
            set { SetValue(value); }
        }

        public String Selector
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

    }
}
