//Autogenerated by SSDCPortal.EntityGenerator
using SSDCPortal.Constants;
using SSDCPortal.Shared.DataInterfaces;
using Breeze.Sharp;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace SSDCPortal.Shared.Dto.Db
{
    public partial class TenantSetting : BaseEntity, ITenantSetting
    {
        public String TenantId
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public SettingKey Key
        {
            get { return GetValue<SettingKey>(); }
            set { SetValue(value); }
        }

        public String Value
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public SettingType Type
        {
            get { return GetValue<SettingType>(); }
            set { SetValue(value); }
        }

    }
}
