//Autogenerated by SSDCPortal.EntityGenerator
using SSDCPortal.Constants;
using SSDCPortal.Shared.DataInterfaces;
using Breeze.Sharp;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace SSDCPortal.Shared.Dto.Db
{
    public partial class UserProfile : BaseEntity, IUserProfile
    {
        public Int64 Id
        {
            get { return GetValue<Int64>(); }
            set { SetValue(value); }
        }

        public Guid UserId
        {
            get { return GetValue<Guid>(); }
            set { SetValue(value); }
        }

        IApplicationUser IUserProfile.ApplicationUser { get => ApplicationUser; set => ApplicationUser = (ApplicationUser)value; }

        public ApplicationUser ApplicationUser
        {
            get { return GetValue<ApplicationUser>(); }
            set { SetValue(value); }
        }

        public String LastPageVisited
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public Boolean IsNavOpen
        {
            get { return GetValue<Boolean>(); }
            set { SetValue(value); }
        }

        public Boolean IsNavMinified
        {
            get { return GetValue<Boolean>(); }
            set { SetValue(value); }
        }

        public Int32 Count
        {
            get { return GetValue<Int32>(); }
            set { SetValue(value); }
        }

        public DateTime LastUpdatedDate
        {
            get { return GetValue<DateTime>(); }
            set { SetValue(value); }
        }

        public String TenantId
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

    }
}
