//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("EnkodeLLC")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Blazor Boilerplate is starter kit / SPA Admin Template for Blazor")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2.1.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2.1.0")]
[assembly: System.Reflection.AssemblyProductAttribute("SSDCPortal.Client")]
[assembly: System.Reflection.AssemblyTitleAttribute("SSDCPortal.Client")]
[assembly: System.Reflection.AssemblyVersionAttribute("2.1.0.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/enkodellc/blazorboilerplate")]

// Generated by the MSBuild WriteCodeFragment class.

